# Pipeline
plan <- drake_plan(
  brik <- brick_from_path("./data"),
  brik_cellids <- build_cellids(brik),
  brik <- addLayer(brik, harmonize(brik_cellids, brik)),
  bbox <- bbox_from_raster(brik),
  gbif_query <- occ_search(scientificName="Panthera onca",
                           geometry=bbox,
                           eventDate="2000,2019",
                           hasCoordinate = TRUE,
                           hasGeospatialIssue = FALSE),
  gbif_points <- records_to_spatial(gbif_query, projection(brik)),
  gbif_points_cellids <- extract_unique(brik_cellids, gbif_points),
  brik_table <- data.frame(rasterToPoints(brik)),
  brik_table <- brik_table[complete.cases(brik_table), ],
  brik_table$sp <- NA,
  brik_table$sp[brik_table$id %in% gbif_points_cellids] <- 1,
  brik_table$sp <- add_pseudoabsence(brik_table, 3000),
  #brik_table$id <- NA,
  train_table <- brik_table[!is.na(brik_table$sp),],
  sampsize <- calc_sample_size(train_table$sp),
  rf_model <- randomForest(y=as.factor(train_table$sp),
                           x=train_table[3:(ncol(train_table)-1)],
                           sampsize = c(sampsize,sampsize)),
  sdm_prediction <- predict(rf_model,brik_table[3:(ncol(brik_table)-1)],
                          type="prob"),
  output_df <- data.frame(x=brik_table$x,y=brik_table$y,sdm_prob=sdm_prediction[,2]),
  output_raster <- raster_from_points(output_df,projection(brik)),
  writeOGR(gbif_points, "sp_points.shp", "sp_points", 
           driver="ESRI Shapefile", overwrite_layer = TRUE),
  writeRaster(output_raster, filename="sdm.tif", format="GTiff", overwrite=TRUE)
)
